In [ ]:
import torch

In [5]:
# Check PyTorch version and CUDA availability
print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())

2.9.0+cu130
13.0
True


# A.2 Understanding Tensors

## A.2.1 Scalars, vectores, matrices, and tensors

In [36]:
# To create a 0-D, 1-D, 2-D, and 3-D tensor in PyTorch:
tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1, 2, 3])
tensor2d = torch.tensor([[1, 2], [3, 4]])
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(f"0-D tensor (scalar) from a Python integer: {tensor0d}")
print(f"1-D tensor (vector) from a Python list: {tensor1d}")
print(f"2-D tensor from a nested Python list: {tensor2d}")
print(f"3-D tensor from a nested Python list: {tensor3d}")

0-D tensor (scalar) from a Python integer: 1
1-D tensor (vector) from a Python list: tensor([1, 2, 3])
2-D tensor from a nested Python list: tensor([[1, 2],
        [3, 4]])
3-D tensor from a nested Python list: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


## A.2.2 Tensor data types

#### By default, python integers create tensors of dtype torch.int64

In [37]:
print(tensor1d.dtype)

torch.int64


#### By default, python floats create tensors of dtype torch.float32

In [38]:
tensor1d_float = torch.tensor([1.0, 2.0, 3.0])
print(tensor1d_float.dtype)

torch.float32


> **Note**: GPU architectures are optimized for 32-bit computations

#### To change a tensor's dtype, use the .to() method

In [39]:
tensor1d_float64 = tensor1d_float.to(torch.float64)
print(tensor1d_float64.dtype)

torch.float64


## A.2.3 Common PyTorch tensor operations

#### Create new tensors

In [40]:
tensor2d = torch.tensor([[1, 2], [3, 4]])

#### Reshape tensors

In [45]:
print(tensor2d)
print(tensor2d.shape)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


In [ ]:
print(tensor2d.reshape(4, 1))
print(tensor2d.view(4, 1))  # Both are similar

tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [43]:
print(tensor2d.T)  # Transpose

tensor([[1, 3],
        [2, 4]])


#### Matrix Multiplication

In [46]:
print(tensor2d.matmul(tensor2d.T))
print(tensor2d @ tensor2d.T)  # Both are similar

tensor([[ 5, 11],
        [11, 25]])
tensor([[ 5, 11],
        [11, 25]])


# A.3 Seeing models as computation graphs

#### A logistic regression forward pass

In [ ]:
import torch.nn.functional as F  # For activation functions

y = torch.tensor([1.0])  # Target label
x1 = torch.tensor([1.1])  # Input feature
w1 = torch.tensor([2.2])  # Weight
b = torch.tensor([0.0])  # Bias

z = x1 * w1 + b  # Linear transformation (logits)
y_pred = torch.sigmoid(z)  # Sigmoid activation

loss = F.binary_cross_entropy(y_pred, y)  # Binary cross-entropy loss

print(loss)

tensor(0.0852)
