In [57]:
import torch

In [58]:
# Check PyTorch version and CUDA availability
print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())

2.9.0+cu130
13.0
True


# A.2 Understanding Tensors

## Scalars, vectores, matrices, and tensors

In [59]:
# To create a 0-D, 1-D, 2-D, and 3-D tensor in PyTorch:
tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1, 2, 3])
tensor2d = torch.tensor([[1, 2], [3, 4]])
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tensor4d = torch.tensor(
    [
        [
            [[1, 2, 9, 9], [3, 4, 9, 9]],
            [[5, 6, 9, 9], [7, 8, 9, 9]],
            [[5, 6, 9, 9], [7, 8, 9, 9]],
        ],
        [
            [[1, 2, 9, 9], [3, 4, 9, 9]],
            [[5, 6, 9, 9], [7, 8, 9, 9]],
            [[5, 6, 9, 9], [7, 8, 9, 9]],
        ],
        [
            [[1, 2, 9, 9], [3, 4, 9, 9]],
            [[5, 6, 9, 9], [7, 8, 9, 9]],
            [[5, 6, 9, 9], [7, 8, 9, 9]],
        ],
    ]
)

print(
    f"0-D tensor (scalar) from a Python integer: {tensor0d}, having shape {tensor0d.size()}, dimension = {tensor0d.dim()}"
)
print(
    f"1-D tensor (vector) from a Python list: {tensor1d}, having shape {tensor1d.size()}, dimension = {tensor1d.dim()}"
)
print(
    f"2-D tensor from a nested Python list: {tensor2d}, having shape {tensor2d.size()}, dimension = {tensor2d.dim()}"
)
print(
    f"3-D tensor from a nested Python list: {tensor3d}, having shape {tensor3d.size()}, dimension = {tensor3d.dim()}"
)
print(
    f"4-D tensor from a nested Python list: {tensor4d}, having shape {tensor4d.size()}, dimension = {tensor4d.dim()}"
)

0-D tensor (scalar) from a Python integer: 1, having shape torch.Size([]), dimension = 0
1-D tensor (vector) from a Python list: tensor([1, 2, 3]), having shape torch.Size([3]), dimension = 1
2-D tensor from a nested Python list: tensor([[1, 2],
        [3, 4]]), having shape torch.Size([2, 2]), dimension = 2
3-D tensor from a nested Python list: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]), having shape torch.Size([2, 2, 2]), dimension = 3
4-D tensor from a nested Python list: tensor([[[[1, 2, 9, 9],
          [3, 4, 9, 9]],

         [[5, 6, 9, 9],
          [7, 8, 9, 9]],

         [[5, 6, 9, 9],
          [7, 8, 9, 9]]],


        [[[1, 2, 9, 9],
          [3, 4, 9, 9]],

         [[5, 6, 9, 9],
          [7, 8, 9, 9]],

         [[5, 6, 9, 9],
          [7, 8, 9, 9]]],


        [[[1, 2, 9, 9],
          [3, 4, 9, 9]],

         [[5, 6, 9, 9],
          [7, 8, 9, 9]],

         [[5, 6, 9, 9],
          [7, 8, 9, 9]]]]), having shape torch.Size([3, 3, 2, 

## Tensor data types

> By default, python *integers* create tensors of dtype torch.int64

In [60]:
print(tensor0d.dtype)
print(tensor1d.dtype)
print(tensor2d.dtype)
print(tensor3d.dtype)
print(tensor4d.dtype)

torch.int64
torch.int64
torch.int64
torch.int64
torch.int64


> By default, python *floats* create tensors of dtype torch.float32

In [61]:
tensor1d_float = torch.tensor([1.0, 2.0, 3.0])
print(tensor1d_float.dtype)

torch.float32


> **Note**: GPU architectures are optimized for 32-bit computations

> To change a tensor's dtype, use the .to() method

In [62]:
tensor1d_float64 = tensor1d_float.to(torch.float64)
print(tensor1d_float64.dtype)

torch.float64


## Common PyTorch tensor operations

### Create new tensors

In [63]:
tensor2d = torch.tensor([[1, 2], [3, 4]])

### Reshape tensors

In [64]:
print(tensor2d)
print(tensor2d.shape)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


In [65]:
print(tensor2d.reshape(4, 1))
print(tensor2d.view(4, 1))  # Both are similar

tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [66]:
print(tensor2d.T)  # Transpose

tensor([[1, 3],
        [2, 4]])


### Matrix Multiplication

In [67]:
print(tensor2d.matmul(tensor2d.T))
print(tensor2d @ tensor2d.T)  # Both are similar

tensor([[ 5, 11],
        [11, 25]])
tensor([[ 5, 11],
        [11, 25]])


# A.3 Seeing models as computation graphs

### A logistic regression forward pass

In [68]:
import torch.nn.functional as F  # For activation functions

y = torch.tensor([1.0])  # Target label
print(f"y = {y}, dtype = {y.dtype}")

x1 = torch.tensor([1.1])  # Input feature
print(f"x1 = {x1}, dtype = {x1.dtype}")

w1 = torch.tensor([2.2])  # Weight
print(f"w1 = {w1}, dtype = {w1.dtype}")

b = torch.tensor([0.0])  # Bias
print(f"b = {b}, dtype = {b.dtype}")

z = x1 * w1 + b  # Linear transformation (logits)
print(f"z = {z}, dtype = {z.dtype}")

a = torch.sigmoid(z)  # Sigmoid activation
print(f"a = {a}, dtype = {a.dtype}")

loss = F.binary_cross_entropy(a, y)  # Binary cross-entropy loss
print(f"loss = {loss}, dtype = {loss.dtype}")

y = tensor([1.]), dtype = torch.float32
x1 = tensor([1.1000]), dtype = torch.float32
w1 = tensor([2.2000]), dtype = torch.float32
b = tensor([0.]), dtype = torch.float32
z = tensor([2.4200]), dtype = torch.float32
a = tensor([0.9183]), dtype = torch.float32
loss = 0.0851878821849823, dtype = torch.float32


# A.4 Automatic differentiation made easy

> **Note**: PyTorch will build a computation graph internally by default if one of its terminal nodes has the `requires_grad = True`.

### Computing gradients via autograd

In [69]:
import torch.nn.functional as F
from torch.autograd import (
    grad,
)  # Manual grad function helpful for experimentation, debugging, and understanding autograd mechanics.

y = torch.tensor([1.0])  # Target label
print(f"y = {y}")

x1 = torch.tensor([1.1])  # Input feature
print(f"x1 = {x1}")

w1 = torch.tensor([2.2], requires_grad=True)  # Weight
print(f"w1 = {w1}")

b = torch.tensor([0.0], requires_grad=True)  # Bias
print(f"b = {b}")

z = x1 * w1 + b  # Linear transformation (logits)
print(f"z = {z}")

a = torch.sigmoid(z)  # Sigmoid activation
print(f"a = {a}")

loss = F.binary_cross_entropy(a, y)  # Binary cross-entropy loss
print(f"loss = {loss}")

grad_L_w1 = grad(loss, w1, retain_graph=True)  # Compute gradient of loss w.r.t w1
print(f"Gradient of loss w.r.t w1: {grad_L_w1}")

grad_L_b = grad(loss, b, retain_graph=True)  # Compute gradient of loss w.r.t b
print(f"Gradient of loss w.r.t b: {grad_L_b}")

loss.backward()  # Backpropagation to compute gradients
print(f"Gradient of loss w.r.t w1 using backward(): {w1.grad}")
print(f"Gradient of loss w.r.t b using backward(): {b.grad}")

y = tensor([1.])
x1 = tensor([1.1000])
w1 = tensor([2.2000], requires_grad=True)
b = tensor([0.], requires_grad=True)
z = tensor([2.4200], grad_fn=<AddBackward0>)
a = tensor([0.9183], grad_fn=<SigmoidBackward0>)
loss = 0.0851878821849823
Gradient of loss w.r.t w1: (tensor([-0.0898]),)
Gradient of loss w.r.t b: (tensor([-0.0817]),)
Gradient of loss w.r.t w1 using backward(): tensor([-0.0898])
Gradient of loss w.r.t b using backward(): tensor([-0.0817])


# A.5 Implementing multilayer neural networks

In [70]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()  # Initialize the base class
        self.hidden_layer_1 = torch.nn.Linear(num_inputs, 30)
        self.hidden_layer_2 = torch.nn.Linear(30, 20)
        self.output_layer = torch.nn.Linear(20, num_outputs)

        self.network = torch.nn.Sequential(
            self.hidden_layer_1,
            torch.nn.ReLU(),
            self.hidden_layer_2,
            torch.nn.ReLU(),
            self.output_layer,
        )

    def forward(self, x):
        logits = self.network(x)
        return logits


torch.manual_seed(123)
model = NeuralNetwork(50, 3)

> After instantiating `self.layers = Sequential(...)` in the `__init__` constructor, we just have to call the `self.layers` instead of calling each layer individually in the `NeuralNetwork`'s `forward`
method.

In [71]:
print(model)

NeuralNetwork(
  (hidden_layer_1): Linear(in_features=50, out_features=30, bias=True)
  (hidden_layer_2): Linear(in_features=30, out_features=20, bias=True)
  (output_layer): Linear(in_features=20, out_features=3, bias=True)
  (network): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [72]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Total number of trainable parameters in the model: {num_params}")

Total number of trainable parameters in the model: 2213


> Note that each parameter for which `requires_grad=True` counts as a trainable parameter and will be updated during training

In [73]:
print(model.network[0].weight)
print(model.network[0].weight.shape)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)
torch.Size([30, 50])


In [74]:
print(model.network[0].bias)
print(model.network[0].bias.shape)

Parameter containing:
tensor([-0.1250,  0.0513,  0.0366,  0.0075,  0.0509,  0.0545, -0.0393,  0.0924,
        -0.1412, -0.1232, -0.1063,  0.0081, -0.1249,  0.0101, -0.0019, -0.1298,
         0.1388, -0.0330,  0.1017,  0.1247, -0.0554, -0.0417,  0.1388,  0.0159,
         0.1215,  0.0385,  0.0769, -0.1224, -0.0279,  0.0991],
       requires_grad=True)
torch.Size([30])


In [75]:
torch.manual_seed(123)
X = torch.rand((1, 50))
print(X)

tensor([[0.2961, 0.5166, 0.2517, 0.6886, 0.0740, 0.8665, 0.1366, 0.1025, 0.1841,
         0.7264, 0.3153, 0.6871, 0.0756, 0.1966, 0.3164, 0.4017, 0.1186, 0.8274,
         0.3821, 0.6605, 0.8536, 0.5932, 0.6367, 0.9826, 0.2745, 0.6584, 0.2775,
         0.8573, 0.8993, 0.0390, 0.9268, 0.7388, 0.7179, 0.7058, 0.9156, 0.4340,
         0.0772, 0.3565, 0.1479, 0.5331, 0.4066, 0.2318, 0.4545, 0.9737, 0.4606,
         0.5159, 0.4220, 0.5786, 0.9455, 0.8057]])


In [76]:
out = model(X)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)


> when we use a model for inference (for instance, making predictions) rather than training, it is a best practice to use the `torch.no_grad()`

In [77]:
with torch.no_grad():
    out = model(X)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]])


In [78]:
with torch.no_grad():
    out = torch.softmax(model(X), dim=1)
print(out)

tensor([[0.3113, 0.3934, 0.2952]])


# A.6 Setting up efficient data loaders

### Custom Dataset class

In [79]:
X_train = torch.tensor(
    [
        [-1.2, 3.1],
        [-0.9, 2.9],
        [-0.5, 2.6],
        [2.3, -1.1],
        [2.7, -1.5],
    ]
)

y_train = torch.tensor([0, 0, 0, 1, 1])

X_test = torch.tensor(
    [
        [-0.8, 2.8],
        [2.6, -1.6],
    ]
)

y_test = torch.tensor([0, 1])

In [ ]:
from torch.utils.data import Dataset


class ToyDataset(Dataset):  # 3 main components: __init__, __getitem__, __len__
    def __init__(self, X, y):
        self.features = X
        self.labels = y

    def __getitem__(self, index):
        one_x = self.features[index]
        one_y = self.labels[index]
        return one_x, one_y

    def __len__(self):
        return self.labels.shape[0]


train_ds = ToyDataset(X_train, y_train)
test_ds = ToyDataset(X_test, y_test)

In [89]:
print(f"Number of samples in training dataset: {len(train_ds)}")

Number of samples in training dataset: 5


### Data Loaders

In [91]:
from torch.utils.data import DataLoader

torch.manual_seed(123)

# Create DataLoader objects for batching and shuffling
train_loader = DataLoader(dataset=train_ds, batch_size=2, shuffle=True, num_workers=0)
test_loader = DataLoader(dataset=test_ds, batch_size=2, shuffle=False, num_workers=0)

In [96]:
# Iterate through the training DataLoader and print batches
for idx, (batch_x, batch_y) in enumerate(train_loader):
    print(f"Batch {idx + 1}:")
    print(f"Features:\n{batch_x}")
    print(f"Labels:\n{batch_y}\n")

Batch 1:
Features:
tensor([[-0.5000,  2.6000],
        [ 2.7000, -1.5000]])
Labels:
tensor([0, 1])

Batch 2:
Features:
tensor([[-0.9000,  2.9000],
        [ 2.3000, -1.1000]])
Labels:
tensor([0, 1])

Batch 3:
Features:
tensor([[-1.2000,  3.1000]])
Labels:
tensor([0])



> It is recommended to set `drop_last=True` in the DataLoader during training to ensure that all batches are of equal size, which can help maintain consistency during the training process.

In [98]:
train_loader = DataLoader(
    dataset=train_ds, batch_size=2, shuffle=True, num_workers=0, drop_last=True
)

In [99]:
# Iterate through the training DataLoader and print batches
for idx, (batch_x, batch_y) in enumerate(train_loader):
    print(f"Batch {idx + 1}:")
    print(f"Features:\n{batch_x}")
    print(f"Labels:\n{batch_y}\n")

Batch 1:
Features:
tensor([[ 2.3000, -1.1000],
        [-1.2000,  3.1000]])
Labels:
tensor([1, 0])

Batch 2:
Features:
tensor([[-0.5000,  2.6000],
        [ 2.7000, -1.5000]])
Labels:
tensor([0, 1])



# A.7 A typical training loop

In [112]:
import torch.nn.functional as F

torch.manual_seed(123)

model = NeuralNetwork(num_inputs=2, num_outputs=2)  # Re-initialize the model
optimizer = torch.optim.SGD(
    model.parameters(), lr=0.5
)  # Tell the optimizer which parameters to optimize

num_epochs = 3

for epoch in range(num_epochs):
    model.train()  # Set the model to training mode
    for batch_idx, (features, labels) in enumerate(train_loader):
        optimizer.zero_grad()  # Clear previous gradients to prevent unintended gradient accumulation
        logits = model(features)  # Forward pass
        loss = F.cross_entropy(logits, labels)  # Compute loss
        loss.backward()  # Backpropagation
        optimizer.step()  # Update model parameters (previous weights)

        # Logging
        print(
            f"Epoch: {epoch + 1:03d}/{num_epochs:03d}"
            f" | Batch: {batch_idx + 1:03d}/{len(train_loader):03d}"
            f" | Train Loss: {loss:.2f}"
        )

Epoch: 001/003 | Batch: 001/002 | Train Loss: 0.75
Epoch: 001/003 | Batch: 002/002 | Train Loss: 0.65
Epoch: 002/003 | Batch: 001/002 | Train Loss: 0.44
Epoch: 002/003 | Batch: 002/002 | Train Loss: 0.13
Epoch: 003/003 | Batch: 001/002 | Train Loss: 0.03
Epoch: 003/003 | Batch: 002/002 | Train Loss: 0.00


In [113]:
print(sum(p.numel() for p in model.parameters() if p.requires_grad))

752


In [114]:
model.eval()  # Set the model to evaluation mode
with torch.no_grad():  # Disable gradient computation for evaluation
    outputs = model(X_train)
print(outputs)

tensor([[ 2.8569, -4.1618],
        [ 2.5382, -3.7548],
        [ 2.0944, -3.1820],
        [-1.4814,  1.4816],
        [-1.7176,  1.7342]])


In [ ]:
torch.set_printoptions(
    sci_mode=False
)  # Disable scientific notation for better readability
probs = torch.softmax(
    outputs, dim=1
)  # Convert logits to probabilities where dim means axis along which softmax is computed
print(probs)

tensor([[0.9991, 0.0009],
        [0.9982, 0.0018],
        [0.9949, 0.0051],
        [0.0491, 0.9509],
        [0.0307, 0.9693]])


In [ ]:
predicted_classes = torch.argmax(
    probs, dim=1
)  # Get the class with the highest probability per row
print(predicted_classes)

tensor([0, 0, 0, 1, 1])


In [125]:
print(predicted_classes == y_train)
print(torch.sum(predicted_classes == y_train))  # Accuracy

tensor([True, True, True, True, True])
tensor(5)


> Function to compute the prediction accuracy

In [ ]:
def compute_accuracy(model, dataloader):
    pass