In [2]:
import torch

In [3]:
# Check PyTorch version and CUDA availability
print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())

2.9.0+cu130
13.0
True


# A.2 Understanding Tensors

## A.2.1 Scalars, vectores, matrices, and tensors

In [ ]:
# To create a 0-D, 1-D, 2-D, and 3-D tensor in PyTorch:
tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1, 2, 3])
tensor2d = torch.tensor([[1, 2], [3, 4]])
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tensor4d = torch.tensor(
    [
        [
            [[1, 2, 9, 9], [3, 4, 9, 9]],
            [[5, 6, 9, 9], [7, 8, 9, 9]],
            [[5, 6, 9, 9], [7, 8, 9, 9]],
        ],
        [
            [[1, 2, 9, 9], [3, 4, 9, 9]],
            [[5, 6, 9, 9], [7, 8, 9, 9]],
            [[5, 6, 9, 9], [7, 8, 9, 9]],
        ],
        [
            [[1, 2, 9, 9], [3, 4, 9, 9]],
            [[5, 6, 9, 9], [7, 8, 9, 9]],
            [[5, 6, 9, 9], [7, 8, 9, 9]],
        ],
    ]
)

print(
    f"0-D tensor (scalar) from a Python integer: {tensor0d}, having shape {tensor0d.size()}, dimension = {tensor0d.dim()}"
)
print(
    f"1-D tensor (vector) from a Python list: {tensor1d}, having shape {tensor1d.size()}, dimension = {tensor1d.dim()}"
)
print(
    f"2-D tensor from a nested Python list: {tensor2d}, having shape {tensor2d.size()}, dimension = {tensor2d.dim()}"
)
print(
    f"3-D tensor from a nested Python list: {tensor3d}, having shape {tensor3d.size()}, dimension = {tensor3d.dim()}"
)
print(
    f"4-D tensor from a nested Python list: {tensor4d}, having shape {tensor4d.size()}, dimension = {tensor4d.dim()}"
)

0-D tensor (scalar) from a Python integer: 1, having shape torch.Size([]), dimension = 0
1-D tensor (vector) from a Python list: tensor([1, 2, 3]), having shape torch.Size([3]), dimension = 1
2-D tensor from a nested Python list: tensor([[1, 2],
        [3, 4]]), having shape torch.Size([2, 2]), dimension = 2
3-D tensor from a nested Python list: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]), having shape torch.Size([2, 2, 2]), dimension = 3
4-D tensor from a nested Python list: tensor([[[[1, 2, 9, 9],
          [3, 4, 9, 9]],

         [[5, 6, 9, 9],
          [7, 8, 9, 9]],

         [[5, 6, 9, 9],
          [7, 8, 9, 9]]],


        [[[1, 2, 9, 9],
          [3, 4, 9, 9]],

         [[5, 6, 9, 9],
          [7, 8, 9, 9]],

         [[5, 6, 9, 9],
          [7, 8, 9, 9]]],


        [[[1, 2, 9, 9],
          [3, 4, 9, 9]],

         [[5, 6, 9, 9],
          [7, 8, 9, 9]],

         [[5, 6, 9, 9],
          [7, 8, 9, 9]]]]), having shape torch.Size([3, 3, 2, 

## A.2.2 Tensor data types

#### By default, python *integers* create tensors of dtype torch.int64

In [34]:
print(tensor0d.dtype)
print(tensor1d.dtype)
print(tensor2d.dtype)
print(tensor3d.dtype)
print(tensor4d.dtype)

torch.int64
torch.int64
torch.int64
torch.int64
torch.int64


#### By default, python *floats* create tensors of dtype torch.float32

In [36]:
tensor1d_float = torch.tensor([1.0, 2.0, 3.0])
print(tensor1d_float.dtype)

torch.float32


> **Note**: GPU architectures are optimized for 32-bit computations

#### To change a tensor's dtype, use the .to() method

In [37]:
tensor1d_float64 = tensor1d_float.to(torch.float64)
print(tensor1d_float64.dtype)

torch.float64


## A.2.3 Common PyTorch tensor operations

#### Create new tensors

In [38]:
tensor2d = torch.tensor([[1, 2], [3, 4]])

#### Reshape tensors

In [39]:
print(tensor2d)
print(tensor2d.shape)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


In [ ]:
print(tensor2d.reshape(4, 1))
print(tensor2d.view(4, 1))  # Both are similar

tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [ ]:
print(tensor2d.T)  # Transpose

tensor([[1, 3],
        [2, 4]])


#### Matrix Multiplication

In [59]:
print(tensor2d.matmul(tensor2d.T))
print(tensor2d @ tensor2d.T)  # Both are similar

tensor([[ 5, 11],
        [11, 25]])
tensor([[ 5, 11],
        [11, 25]])


# A.3 Seeing models as computation graphs

#### A logistic regression forward pass

In [ ]:
import torch.nn.functional as F  # For activation functions

y = torch.tensor([1.0])  # Target label
print(f"y = {y}, datatype = {y.dtype}")

x1 = torch.tensor([1.1])  # Input feature
print(f"x1 = {x1}, datatype = {x1.dtype}")

w1 = torch.tensor([2.2])  # Weight
print(f"w1 = {w1}, datatype = {w1.dtype}")

b = torch.tensor([0.0])  # Bias
print(f"b = {b}, datatype = {b.dtype}")


z = x1 * w1 + b  # Linear transformation (logits)
a = torch.sigmoid(z)  # Sigmoid activation

loss = F.binary_cross_entropy(a, y)  # Binary cross-entropy loss

print(loss)

y = tensor([1.]), datatype = torch.float32
x1 = tensor([1.1000])
w1 = tensor([2.2000])
b = tensor([0.])
tensor(0.0852)


# A.4 Automatic differentiation made easy

> **Note**: PyTorch will build a computation graph internally by default if one of its terminal nodes has the `requires_grad = True`.